DROP TABLE IF EXISTS Personnel CASCADE;
DROP TABLE IF EXISTS Unit CASCADE;
DROP TABLE IF EXISTS Branch CASCADE;

CREATE TABLE Branch (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT
);

CREATE TABLE Unit (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(100),
    parent_unit_id INTEGER,
    branch_id INTEGER NOT NULL,
    location VARCHAR(255),
    founded_year INTEGER,
    FOREIGN KEY (parent_unit_id) REFERENCES Unit(id) ON DELETE SET NULL,
    FOREIGN KEY (branch_id) REFERENCES Branch(id) ON DELETE CASCADE
);

CREATE TABLE Personnel (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    rank VARCHAR(100) NOT NULL,
    rang_code VARCHAR(10) NOT NULL,
    position VARCHAR(255) NOT NULL,
    unit_id INTEGER NOT NULL,
    service_number VARCHAR(50),
    FOREIGN KEY (unit_id) REFERENCES Unit(id) ON DELETE CASCADE
);

INSERT INTO Branch (name, description) VALUES
('Esercito Italiano', 'Italienisches Heer - Landstreitkräfte'),
('Aeronautica Militare', 'Italienische Luftwaffe'),
('Marina Militare', 'Italienische Marine'),
('Carabinieri', 'Italienische Gendarmerie');

INSERT INTO Unit (id, name, type, parent_unit_id, branch_id, location, founded_year) VALUES
(1, 'Stato Maggiore dell''Esercito', 'Oberkommando', NULL, 1, 'Rom', 1861),
(2, 'Comando delle Forze Operative Nord', 'Korps', 1, 1, 'Mailand', 2013),
(3, 'Comando delle Forze Operative Sud', 'Korps', 1, 1, 'Neapel', 2013),
(4, 'Comando delle Forze Operative Versatile', 'Korps', 1, 1, 'Rom', 2022),
(5, 'Comando della Logistica dell''Esercito', 'Logistik', 1, 1, 'Rom', 1997),
(6, 'Comando delle Trasmissioni', 'Fernmeldewesen', 1, 1, 'Anzio', 1925),
(7, 'Divisione "Acqui"', 'Division', 2, 1, 'San Giorgio a Cremano', 1939),
(8, 'Divisione "Pozzuolo del Friuli"', 'Division', 2, 1, 'Florenz', 1963),
(9, 'Divisione "Aosta"', 'Division', 3, 1, 'Messina', 1934),
(10, 'Brigata "Granatieri di Sardegna"', 'Brigade', 3, 1, 'Rom', 1831),
(11, 'Comando delle Forze Speciali dell''Esercito', 'Spezialkräfte', 4, 1, 'Pisa', 2004),
(12, 'Brigata Alpina "Taurinense"', 'Gebirgsbrigade', 7, 1, 'Turin', 1882),
(13, 'Brigata Meccanizzata "Pinerolo"', 'Mechanisierte Brigade', 7, 1, 'Bari', 1831),
(14, 'Brigata Cavalleria "Pozzuolo del Friuli"', 'Kavalleriebrigade', 8, 1, 'Gorizia', 1920),
(15, 'Brigata Aeromobile "Friuli"', 'Luftbewegliche Brigade', 8, 1, 'Bologna', 1963),
(16, '9° Reggimento d''Assalto Paracadutisti "Col Moschin"', 'Fallschirmjäger', 11, 1, 'Livorno', 1953),
(17, '2° Reggimento Alpini', 'Gebirgsjäger', 12, 1, 'Cuneo', 1882),
(18, '3° Reggimento Alpini', 'Gebirgsjäger', 12, 1, 'Pinerolo', 1882),
(19, '9° Reggimento Alpini', 'Gebirgsjäger', 12, 1, 'L''Aquila', 1883),
(20, '1° Reggimento Artiglieria Terrestre "Aosta"', 'Artillerie', 13, 1, 'Fossano', 1815),
(21, '82° Reggimento Fanteria "Torino"', 'Infanterie', 13, 1, 'Torino', 1915),
(22, '13° Reggimento Cavalleria "Monferrato"', 'Kavallerie', 14, 1, 'Monferrato', 1859),
(23, '19° Reggimento Cavalleria "Guide"', 'Kavallerie', 14, 1, 'Salerno', 1860),
(24, '5° Reggimento Aviazione dell''Esercito "Rigel"', 'Heeresflieger', 15, 1, 'Casarsa', 1951),
(25, '7° Reggimento Aviazione dell''Esercito "Vega"', 'Heeresflieger', 15, 1, 'Rimini', 1957),
(26, 'Battaglione Alpini "Susa"', 'Gebirgsjäger-Bataillon', 17, 1, 'Susa', 1887),
(27, 'Battaglione Alpini "Mondovì"', 'Gebirgsjäger-Bataillon', 17, 1, 'Mondovì', 1887),
(28, 'Battaglione Alpini "Pinerolo"', 'Gebirgsjäger-Bataillon', 18, 1, 'Pinerolo', 1887),
(29, 'Battaglione Alpini "Fenestrelle"', 'Gebirgsjäger-Bataillon', 18, 1, 'Fenestrelle', 1887),
(30, 'Battaglione Alpini "L''Aquila"', 'Gebirgsjäger-Bataillon', 19, 1, 'L''Aquila', 1887),
(31, 'Battaglione Alpini "Vicenza"', 'Gebirgsjäger-Bataillon', 19, 1, 'Vicenza', 1887),
(32, 'Gruppo Artiglieria "Aosta"', 'Artillerie-Gruppe', 20, 1, 'Fossano', 1950),
(33, 'Gruppo Artiglieria "Pinerolo"', 'Artillerie-Gruppe', 20, 1, 'Torino', 1950),
(34, 'Battaglione Fanteria "Torino"', 'Infanterie-Bataillon', 21, 1, 'Torino', 1950),
(35, 'Battaglione Fanteria "Saluzzo"', 'Infanterie-Bataillon', 21, 1, 'Saluzzo', 1950),
(36, 'Squadrone Carri "Monferrato"', 'Panzer-Schwadron', 22, 1, 'Monferrato', 1960),
(37, 'Squadrone Esplorante "Guide"', 'Aufklärungs-Schwadron', 23, 1, 'Salerno', 1960),
(38, '1° Battaglione Elicotteri "Rigel"', 'Helikopter-Bataillon', 24, 1, 'Casarsa', 1970),
(39, '2° Battaglione Elicotteri "Vega"', 'Helikopter-Bataillon', 25, 1, 'Rimini', 1970),
(40, '1ª Compagnia Alpini "Susa"', 'Gebirgsjäger-Kompanie', 26, 1, 'Susa', 1950),
(41, '2ª Compagnia Alpini "Susa"', 'Gebirgsjäger-Kompanie', 26, 1, 'Susa', 1950),
(42, '1ª Compagnia Alpini "Mondovì"', 'Gebirgsjäger-Kompanie', 27, 1, 'Mondovì', 1950),
(43, '2ª Compagnia Alpini "Mondovì"', 'Gebirgsjäger-Kompanie', 27, 1, 'Mondovì', 1950),
(44, '1ª Compagnia Alpini "Pinerolo"', 'Gebirgsjäger-Kompanie', 28, 1, 'Pinerolo', 1950),
(45, '2ª Compagnia Alpini "Pinerolo"', 'Gebirgsjäger-Kompanie', 28, 1, 'Pinerolo', 1950),
(46, '1ª Compagnia Artiglieria "Aosta"', 'Artillerie-Kompanie', 32, 1, 'Fossano', 1960),
(47, '2ª Compagnia Artiglieria "Aosta"', 'Artillerie-Kompanie', 32, 1, 'Fossano', 1960),
(48, '1ª Compagnia Fanteria "Torino"', 'Infanterie-Kompanie', 34, 1, 'Torino', 1960),
(49, '2ª Compagnia Fanteria "Torino"', 'Infanterie-Kompanie', 34, 1, 'Torino', 1960),
(50, '1° Plotone Carri "Monferrato"', 'Panzer-Zug', 36, 1, 'Monferrato', 1970),
(51, '2° Plotone Carri "Monferrato"', 'Panzer-Zug', 36, 1, 'Monferrato', 1970),
(52, '1° Plotone Elicotteri "Rigel"', 'Helikopter-Zug', 38, 1, 'Casarsa', 1980),
(53, '2° Plotone Elicotteri "Rigel"', 'Helikopter-Zug', 38, 1, 'Casarsa', 1980);

INSERT INTO Personnel (name, rank, rang_code, position, unit_id, service_number) VALUES
('Generale Giuseppe Dragoni', 'Generale', 'OF-9', 'Capo di Stato Maggiore dell''Esercito', 1, 'EI-00001'),
('Generale di Corpo d''Armata Lorenzo D''Addario', 'Generale di Corpo d''Armata', 'OF-8', 'Comandante Forze Operative Nord', 2, 'EI-00002'),
('Generale di Corpo d''Armata Marco Bellini', 'Generale di Corpo d''Armata', 'OF-8', 'Comandante Forze Operative Sud', 3, 'EI-00003'),
('Generale di Divisione Roberto Perretti', 'Generale di Divisione', 'OF-7', 'Comandante Divisione "Acqui"', 7, 'EI-00004'),
('Generale di Divisione Antonio Conti', 'Generale di Divisione', 'OF-7', 'Comandante Divisione "Pozzuolo del Friuli"', 8, 'EI-00005'),
('Generale di Brigata Alessandro Romano', 'Generale di Brigata', 'OF-6', 'Comandante Brigata Alpina "Taurinense"', 12, 'EI-00006'),
('Generale di Brigata Francesco Marino', 'Generale di Brigata', 'OF-6', 'Comandante Brigata "Pinerolo"', 13, 'EI-00007'),
('Colonnello Marco Ferrara', 'Colonnello', 'OF-5', 'Comandante 9° Reggimento "Col Moschin"', 16, 'EI-00008'),
('Colonnello Giovanni Russo', 'Colonnello', 'OF-5', 'Comandante 2° Reggimento Alpini', 17, 'EI-00009'),
('Colonnello Paolo Bianchi', 'Colonnello', 'OF-5', 'Comandante 3° Reggimento Alpini', 18, 'EI-00010'),
('Tenente Colonnello Giovanni Costa', 'Tenente Colonnello', 'OF-4', 'Vice-Comandante Brigata "Pinerolo"', 13, 'EI-00011'),
('Tenente Colonnello Mario Esposito', 'Tenente Colonnello', 'OF-4', 'Comandante Battaglione "Susa"', 26, 'EI-00012'),
('Tenente Colonnello Luca Romano', 'Tenente Colonnello', 'OF-4', 'Comandante Battaglione "Mondovì"', 27, 'EI-00013'),
('Maggiore Francesco De Santis', 'Maggiore', 'OF-3', 'Capo Ufficio Operazioni', 8, 'EI-00014'),
('Maggiore Antonio Gallo', 'Maggiore', 'OF-3', 'Comandante 1ª Compagnia Alpini "Susa"', 40, 'EI-00015'),
('Maggiore Riccardo Moretti', 'Maggiore', 'OF-3', 'Comandante 1ª Compagnia Artiglieria "Aosta"', 46, 'EI-00016'),
('Capitano Andrea Marini', 'Capitano', 'OF-2', 'Comandante Compagnia', 12, 'EI-00017'),
('Capitano Davide Ferrari', 'Capitano', 'OF-2', 'Comandante 2ª Compagnia Alpini "Susa"', 41, 'EI-00018'),
('Capitano Simone Barbieri', 'Capitano', 'OF-2', 'Comandante 1° Plotone Carri', 50, 'EI-00019'),
('Tenente Luca Barbieri', 'Tenente', 'OF-1', 'Vice-Comandante Compagnia', 14, 'EI-00020'),
('Tenente Matteo Ricci', 'Tenente', 'OF-1', 'Comandante 1° Plotone Elicotteri', 52, 'EI-00021'),
('Tenente Giorgio Martini', 'Tenente', 'OF-1', 'Comandante 2° Plotone Elicotteri', 53, 'EI-00022'),
('Primo Maresciallo Luogotenente Stefano Gallo', 'Primo Maresciallo Luogotenente', 'OR-9', 'Capo Ufficio Personale', 1, 'EI-00023'),
('Primo Maresciallo Luogotenente Roberto Conti', 'Primo Maresciallo Luogotenente', 'OR-9', 'Capo Ufficio Operazioni', 2, 'EI-00024'),
('Primo Maresciallo Antonio Rizzo', 'Primo Maresciallo', 'OR-8', 'Responsabile Logistica', 5, 'EI-00025'),
('Primo Maresciallo Marco Leone', 'Primo Maresciallo', 'OR-8', 'Capo Sezione Addestramento', 12, 'EI-00026'),
('Maresciallo Capo Roberto Moretti', 'Maresciallo Capo', 'OR-8', 'Capo Sezione Trasmissioni', 6, 'EI-00027'),
('Maresciallo Capo Giovanni Santoro', 'Maresciallo Capo', 'OR-8', 'Capo Meccanico Reggimento', 17, 'EI-00028'),
('Maresciallo Ordinario Francesco Greco', 'Maresciallo Ordinario', 'OR-7', 'Responsabile Armamento', 26, 'EI-00029'),
('Maresciallo Ordinario Alessandro Costa', 'Maresciallo Ordinario', 'OR-7', 'Capo Plotone Elicotteri', 38, 'EI-00030'),
('Sergente Maggiore Capo Paolo Marino', 'Sergente Maggiore Capo', 'OR-6', 'Capo Squadra Specialista', 40, 'EI-00031'),
('Sergente Maggiore Alessandro Giordano', 'Sergente Maggiore', 'OR-5', 'Capo Squadra', 13, 'EI-00032'),
('Sergente Maggiore Luca Ferrara', 'Sergente Maggiore', 'OR-5', 'Capo Squadra Artiglieria', 32, 'EI-00033'),
('Sergente Francesco Leone', 'Sergente', 'OR-5', 'Vice Capo Squadra', 14, 'EI-00034'),
('Sergente Matteo Barbieri', 'Sergente', 'OR-5', 'Capo Carrista', 36, 'EI-00035'),
('Sergente Riccardo Romano', 'Sergente', 'OR-5', 'Capo Elicotterista', 52, 'EI-00036'),
('Caporal Maggiore Capo Scelto Riccardo Martini', 'Caporal Maggiore Capo Scelto', 'OR-4', 'Specialista Comunicazioni', 6, 'EI-00037'),
('Caporal Maggiore Capo Scelto Antonio Russo', 'Caporal Maggiore Capo Scelto', 'OR-4', 'Specialista Elettronica', 24, 'EI-00038'),
('Caporal Maggiore Capo Matteo Santoro', 'Caporal Maggiore Capo', 'OR-4', 'Autista Specializzato', 5, 'EI-00039'),
('Caporal Maggiore Capo Giovanni Conti', 'Caporal Maggiore Capo', 'OR-4', 'Specialista Armamento', 40, 'EI-00040'),
('Caporal Maggiore Alessandro Greco', 'Caporal Maggiore', 'OR-3', 'Mitragliere', 12, 'EI-00041'),
('Caporal Maggiore Marco Esposito', 'Caporal Maggiore', 'OR-3', 'Artigliere', 32, 'EI-00042'),
('Caporal Maggiore Luca Bianchi', 'Caporal Maggiore', 'OR-3', 'Carrista', 36, 'EI-00043'),
('Caporal Maggiore Paolo Moretti', 'Caporal Maggiore', 'OR-3', 'Elicotterista', 52, 'EI-00044'),
('Caporale Francesco Ricci', 'Caporale', 'OR-2', 'Alpino', 40, 'EI-00045'),
('Caporale Andrea Gallo', 'Caporale', 'OR-2', 'Artigliere', 46, 'EI-00046'),
('Caporale Simone Marino', 'Caporale', 'OR-2', 'Carrista', 50, 'EI-00047'),
('Caporale Davide Conti', 'Caporale', 'OR-2', 'Elicotterista', 53, 'EI-00048'),
('Soldato Antonio Parisi', 'Soldato', 'OR-1', 'Fante', 13, 'EI-00049'),
('Soldato Mario Rossi', 'Soldato', 'OR-1', 'Alpino', 41, 'EI-00050'),
('Soldato Luigi Ferrari', 'Soldato', 'OR-1', 'Artigliere', 47, 'EI-00051'),
('Soldato Giuseppe Esposito', 'Soldato', 'OR-1', 'Carrista', 51, 'EI-00052'),
('Soldato Giovanni Bianchi', 'Soldato', 'OR-1', 'Elicotterista', 52, 'EI-00053'),
('Soldato Francesco Romano', 'Soldato', 'OR-1', 'Trasmissionista', 6, 'EI-00054'),
('Soldato Andrea Colombo', 'Soldato', 'OR-1', 'Logistico', 5, 'EI-00055'),
('Soldato Marco Ricci', 'Soldato', 'OR-1', 'Autista', 13, 'EI-00056');